config/routes.rb
Rails.application.routes.draw do
  resources :response_umux_lites
  resources :response_umuxes
  resources :app_notifications
  resources :response_sus
  resources :response_attrak_diffs
  resources :response_attrak_diff_abridgeds
  resources :response_deeps
  resources :projects
  devise_for :users
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/index'
  get 'admin/project/:id', to: 'admin#project', as: 'admin_project'

  get 'welcome/index'
  get 'projects/index'

  get 'projects/:id/close', to: 'projects#close', as: 'close_project'
  get 'projects/:id/open', to: 'projects#open', as: 'open_project'

  get 'response_sus/recover/:id', to: 'response_sus#recover', as: 'recover_response_sus'
  get 'response_attrak_diffs/recover/:id', to: 'response_attrak_diffs#recover', as: 'recover_response_attrak_diffs'
  get 'response_attrak_diff_abridgeds/recover/:id', to: 'response_attrak_diff_abridgeds#recover', as: 'recover_response_attrak_diff_abridgeds'
  get 'response_deeps/recover/:id', to: 'response_deeps#recover', as: 'recover_response_deeps'
  get 'response_umuxes/recover/:id', to: 'response_umuxes#recover', as: 'recover_response_umuxes'
  get 'response_umux_lites/recover/:id', to: 'response_umux_lites#recover', as: 'recover_response_umux_lites'

  get 'app_notifications/mark_as_read/:id', to: 'app_notifications#mark_as_read', as: 'mark_notification_as_read'

  get 'sample_sizes/usability_problems'
  get 'timer/index'

  get 'r/success/:locale', to: 'projects#response_saved', as: 'project_public_response_saved'
  get 'r/:uri_token', to: 'projects#respond', as: 'project_public_respond'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admin/index.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section">Projets et utilisateurs</h1>
  </div>
</nav>

<%= flash_messages %>

<div class="ui container">
  <div class="ui pointing secondary menu">
    <a class="item active" data-tab="user_accounts">Utilisateurs</a>
    <a class="item" data-tab="questionnaires">Questionnaires UX</a>
  </div>
  <div class="ui tab active" data-tab="user_accounts">
    <div class="ui segment">
      <div class="ui statistics">
        <div class="statistic">
          <div class="label">
            <%= "Utilisateur".pluralize(@count[:users]) %>
          </div>
          <div class="value">
            <%= @count[:users] %>
          </div>
        </div>
        <div class="statistic">
          <div class="label">
            Dernier compte créé il y a
          </div>
          <div class="value">
            <%= distance_of_time_in_words(@users[:new].first.created_at, DateTime.now) %>
          </div>
        </div>
      </div>
    </div>

    <h2 class="ui header">Top 10 des utilisateurs actifs</h2>
    <table class="ui table">
      <thead>
        <tr>
          <th width="25%">E-mail</th>
          <th>Dernière connexion</th>
          <th class="center aligned">Projets</th>
          <th class="center aligned" width="15%">Connexions</th>
        </tr>
      </thead>
      <tbody>
        <% @users[:active].each do |user|
            css_class = 'basic'
            if (5..49).include?(user.sign_in_count)
              css_class = 'teal'
            elsif user.sign_in_count >= 50
              css_class = 'pink'
            end
        %>
        <tr>
          <td width="25%"><%= user.email %></td>
          <td><%= l user.current_sign_in_at, format: :long %></td>
          <td class="center aligned" width="15%"><%= user.projects.count %></td>
          <td class="center aligned"><span class="ui <%= css_class %> circular label"><%= user.sign_in_count %></span></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <h2 class="ui header">Derniers comptes créés</h2>
    <table class="ui table">
      <thead>
        <tr>
          <th width="25%">E-mail</th>
          <th>Date de création</th>
          <th class="center aligned" width="15%">Projets</th>
        </tr>
      </thead>
      <tbody>
        <% @users[:new].each do |user| %>
        <tr>
          <td width="25%"><%= user.email %></td>
          <td><%= l user.created_at, format: :long %></td>
          <td class="center aligned" width="15%"><%= user.projects.count %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>
  <div class="ui tab" data-tab="questionnaires">
    <div class="ui segment">
      <div class="ui statistics">
        <div class="statistic">
          <div class="label">
            <%= "Projet".pluralize(@count[:projects]) %>
          </div>
          <div class="value">
            <%= @count[:projects] %>
          </div>
        </div>
        <div class="statistic">
          <div class="label">
            <%= "Réponse".pluralize(@count[:responses]) %>
          </div>
          <div class="value">
            <%= @count[:responses] %>
          </div>
        </div>
        <div class="statistic">
          <div class="label">
            Dernier projet créé il y a
          </div>
          <div class="value">
            <%= distance_of_time_in_words(@projects[:new].first.created_at, DateTime.now) %>
          </div>
        </div>
      </div>
    </div>

    <h2 class="ui header">Top des projets actifs (< 1 mois)</h2>
    <table class="ui table">
      <thead>
        <tr>
          <th colspan="2">Projet</th>
          <th>Questionnaire UX</th>
          <th>Date de fin</th>
          <th class="center aligned" width="15%">Réponses</th>
          <th>Dernière réponse il y a</th>
        </tr>
      </thead>
      <tbody>
        <% @projects[:top_active].each do |project, count|
            css_class = 'basic'
            if (5..14).include?(count)
              css_class = 'teal'
            elsif count >= 15
              css_class = 'pink'
            end
        %>
        <tr>
          <td><a href="<%= url_for admin_project_path(project) %>"><%= project.product_name %> - <%= project.project_code %></a></td>
          <td><%= project.product_type %></td>
          <td><%= project.questionnaire_id %> (<%= project.questionnaire_language %>)</td>
          <td><%= end_date_for(project) %><br /><span class="ui tiny basic label"><%= project.user.email %></span></td>
          <td class="center aligned" width="15%"><span class="ui <%= css_class %> circular label"><%= count %></span></td>
          <td><%= distance_of_time_in_words(project.responses.last.created_at, DateTime.now) %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

    <h2 class="ui header">Nouveaux projets</h2>
    <table class="ui table">
      <thead>
        <tr>
          <th colspan="2">Projet</th>
          <th>Questionnaire UX</th>
          <th>Date de création</th>
          <th class="center aligned" width="15%">Réponses</th>
          <th>Dernière réponse le il y a</th>
        </tr>
      </thead>
      <tbody>
        <% @projects[:new].each do |project|
            css_class = 'basic'
            if (5..14).include?(project.responses.count)
              css_class = 'teal'
            elsif project.responses.count >= 15
              css_class = 'pink'
            end
        %>
        <tr>
          <td><a href="<%= url_for admin_project_path(project) %>"><%= project.product_name %> - <%= project.project_code %></a></td>
          <td><%= project.product_type %></td>
          <td><%= project.questionnaire_id %> (<%= project.questionnaire_language %>)</td>
          <td><%= l project.created_at, format: :long %><br /><span class="ui tiny basic label"><%= project.user.email %></span></td>
          <td class="center aligned" width="15%"><span class="ui <%= css_class %> circular label"><%= project.responses.count %></span></td>
          <td><%= distance_of_time_in_words(project.responses.last.created_at, DateTime.now) unless project.responses.count == 0 %></td>
        </tr>
        <% end %>
      </tbody>
    </table>

  </div>

</div>

app/views/admin/project.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= edit_project_path(@project) %>" class="ui right floated primary button disabled">Modifier</a>
    <% if !@project.is_closed %>
    <a href="<%= close_project_path(@project) %>" class="ui right floated left labeled button disabled"><span class="ui green right pointing label">Ouvert</span><span class="ui inverted button">Fermer le projet</span></a>
    <% else %>
    <a href="<%= open_project_path(@project) %>" class="ui right floated left labeled button disabled"><span class="ui red right pointing label">Fermé</span><span class="ui inverted button">Réouvrir le projet</span></a>
    <% end %>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <a href="<%= admin_path %>" class="section">Projets et utilisateurs</a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section"><%= @project.product_name %> - <%= @project.project_code %></h1>
  </div>
</nav>

<%= flash_messages %>
<div class="ui container">
  <div class="ui pointing secondary menu">
    <a class="item <%= "active" unless @project.has_responses? || @back_to_responses %>" data-tab="description">Description</a>
    <a class="item <%= "active" if @project.has_responses? && !@back_to_responses %>" data-tab="results">Résultats</a>
    <a class="item <%= "active" if @back_to_responses %>" data-tab="responses">Réponses</a>
  </div>
  <div class="ui tab <%= "active" unless @project.has_responses? || @back_to_responses %>" data-tab="description">

    <table class="ui very basic table">
      <tbody>
        <tr>
          <td width="20%" nowrap>Questionnaire :</td>
          <td><%= @project.questionnaire_id %> (<%= @project.questionnaire_language %>) - <a href="#" class="show_editor_modal">consulter et modifier la consigne</a></td>
        </tr>
        <tr>
          <td nowrap>Type de produit :</td>
          <td><%= @project.product_type %></td>
        </tr>
        <tr>
          <td nowrap>Statut :</td>
          <td><%= status_full_for(@project) %></td>
        </tr>
        <tr>
          <td nowrap>Date de fin de l'évaluation :</td>
          <td><%= end_date_full_for(@project) %></td>
        </tr>
        <tr>
          <td nowrap>Lien public pour répondre :</td>
          <td><%= link_to project_public_respond_url(@project.uri_token), project_public_respond_path(@project.uri_token) %>
        </tr>
      </tbody>
    </table>
  </div>

  <div class="ui tab <%= "active" if @project.has_responses? && !@back_to_responses %>" data-tab="results">
    <%= render 'projects' + File::SEPARATOR + 'results' + File::SEPARATOR + @project.questionnaire_id_clean, project: @project %>
  </div>

  <div class="ui tab <%= "active" if @back_to_responses %>" data-tab="responses" id="responsesTab">
    <%= render 'projects' + File::SEPARATOR + 'responses' + File::SEPARATOR + @project.questionnaire_id_clean, project: @project %>
  </div>

</div>