config/routes.rb
Rails.application.routes.draw do
  resources :response_umux_lites
  resources :response_umuxes
  resources :app_notifications
  resources :response_sus
  resources :response_attrak_diffs
  resources :response_attrak_diff_abridgeds
  resources :response_deeps
  resources :projects
  devise_for :users
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/index'
  get 'admin/project/:id', to: 'admin#project', as: 'admin_project'

  get 'welcome/index'
  get 'projects/index'

  get 'projects/:id/close', to: 'projects#close', as: 'close_project'
  get 'projects/:id/open', to: 'projects#open', as: 'open_project'

  get 'response_sus/recover/:id', to: 'response_sus#recover', as: 'recover_response_sus'
  get 'response_attrak_diffs/recover/:id', to: 'response_attrak_diffs#recover', as: 'recover_response_attrak_diffs'
  get 'response_attrak_diff_abridgeds/recover/:id', to: 'response_attrak_diff_abridgeds#recover', as: 'recover_response_attrak_diff_abridgeds'
  get 'response_deeps/recover/:id', to: 'response_deeps#recover', as: 'recover_response_deeps'
  get 'response_umuxes/recover/:id', to: 'response_umuxes#recover', as: 'recover_response_umuxes'
  get 'response_umux_lites/recover/:id', to: 'response_umux_lites#recover', as: 'recover_response_umux_lites'

  get 'app_notifications/mark_as_read/:id', to: 'app_notifications#mark_as_read', as: 'mark_notification_as_read'

  get 'sample_sizes/usability_problems'
  get 'timer/index'

  get 'r/success/:locale', to: 'projects#response_saved', as: 'project_public_response_saved'
  get 'r/:uri_token', to: 'projects#respond', as: 'project_public_respond'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:respond, :response_saved]
  before_action :set_project, only: [:show, :edit, :update, :close, :open, :destroy]
  before_action :load_project_data, only: [:show]

  # GET /projects
  # GET /projects.json
  def index
    default = 'date_desc'
    whitelist = ['name_asc', 'name_desc', 'date_asc', 'date_desc']
    @order_by_possible_values = {
      'date_desc' => 'du plus récent au plus ancien',
      'date_asc'  => 'du plus ancien au plus récent',
      'divider'   => '',
      'name_asc'  => 'de A à Z',
      'name_desc'  => 'de Z à A'
    }
    @order_by_selected_value = default
    @projects = current_user.projects.order(created_at: :desc)
    if (params.has_key?(:order_by) && whitelist.include?(params[:order_by]))
      @order_by_selected_value = params[:order_by]
      cookies[:order_projects_by] = params[:order_by]
    else
      if cookies[:order_projects_by] && whitelist.include?(cookies[:order_projects_by])
        @order_by_selected_value = cookies[:order_projects_by]
      end
    end

    case @order_by_selected_value
    when "name_asc"
      @projects = current_user.projects.order(product_name: :asc)
    when "name_desc"
      @projects = current_user.projects.order(product_name: :desc)
    when "date_asc"
      @projects = current_user.projects.order(created_at: :asc)
    when "date_desc"
      @projects = current_user.projects.order(created_at: :desc)
    end

  end

  # GET /projects/1
  # GET /projects/1.csv
  def show
    @show_variability = false
    if cookies[:show_variability] && cookies[:show_variability].to_i > 0
      @show_variability = true
    end
    @ci_level = cookies[:ci_level] || '95%'
    @ci_level_hash_key = 'ci_' + @ci_level[0..1]
    @ci_level_hash_key = @ci_level_hash_key.to_sym

    @back_to_responses = session["back_to_responses"]
    session["back_to_responses"] = nil

    filename = "[Questionnaire UX] - " + @project.product_name + "-" + @project.project_code + " (" + @project.questionnaire_id + ") - #{Date.today}"
    respond_to do |format|
      format.html
      #format.csv { send_data @project.responses.to_csv, filename: filename + ".csv" }
      format.xlsx { response.headers['Content-Disposition'] = 'attachment; filename="' + filename + '.xlsx"' }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # GET /projects/1/close
  def close
    @project.is_closed = true
    @project.save
    respond_to do |format|
      format.html { redirect_back fallback_location: @project }
    end
  end

  # GET /projects/1/open
  def open
    message = nil
    @project.is_closed = false
    if @project.should_get_closed
      @project.end_date = nil
      message = "Le projet a bien été réouvert et la date de fin a été supprimée."
    end
    @project.save
    respond_to do |format|
      format.html { redirect_back fallback_location: @project, notice: message }
    end
  end

  # GET /r/1
  def respond
    @project = Project.find_by uri_token: params[:uri_token]

    #Updates project status if needed
    if @project.should_get_closed
      @project.is_closed = true
      @project.save
    end

    @showForm = false
    @form = ''
    @has_already_responded = has_already_responded(@project)

    if (params.has_key?(:step))
      case @project.questionnaire_id_clean
      when "attrakdiff"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseAttrakDiff.new
        else
        end
      when "attrakdiff_abrege"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseAttrakDiffAbridged.new
        else
        end
      when "system_usability_scale"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseSu.new
        else
        end
      when "deep"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseDeep.new
        else
        end
      when "umux"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseUmux.new
        else
        end
      when "umux_lite"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseUmuxLite.new
        else
        end
      end
    end
    render layout: "public_response"
  end

  # GET /r/success/fr
  # GET /r/success.json/fr
  def response_saved
    @locale = params[:locale]
    @locale = I18n.default_locale unless I18n.locale_available? @locale
    render layout: "public_response"
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if params["redirect_back"] === "true"
      redirect_back = true
    else
      redirect_back = false
    end

    respond_to do |format|
      if @project.update(project_params)
        if redirect_back
          format.html { redirect_back fallback_location: @project, notice: "La modification a bien été enregistrée." }
        else
          format.html { redirect_to @project, notice: 'La modification a bien été enregistrée.' }
        end
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy_fully!
    #@project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Le projet d'évaluation a bien été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:questionnaire_id, :questionnaire_language, :product_type, :product_name, :project_code, :instructions, :end_date, :uri_token, :forbid_multiple_reponses, :ask_user_ideas, :ask_user_summary, :ask_user_age, :ask_user_gender, :ask_user_occupation, :ask_user_first_use_date, :ask_user_group, :ask_user_usage_frequency)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def gender_icon_for(gender)
    html = ''
    if gender == 1
      html = '<i class="icon venus"></i>'
    elsif gender == 2
      html = '<i class="icon mars"></i>'
    end
    html.html_safe
  end

  def gender_graph_stats_for(users_gender_mean)
    html = '-'
    if users_gender_mean > 0
      female_width = ((2 - users_gender_mean)*100).round
      female_percent = ((2 - users_gender_mean)*100).round(2)
      male_width = ((users_gender_mean - 1)*100).round
      male_percent = ((users_gender_mean - 1)*100).round(2)
      split_width = 2
      if female_width < 2
        female_width = 2
        male_width = 96
      elsif male_width < 2
        male_width = 2
        female_width = 96
      else
        female_width = female_width - 1
        male_width = male_width - 1
      end
      html = <<-HTML
        <div class="gender">
          <div class="data">
            <div class="female bar" style="width:#{female_width}%"></div><div class="split bar" style="width:#{split_width}%"></div><div class="male bar" style="width:#{male_width}%"></div>
          </div>
          <div class="label">
            <div class="female"><i class="icon venus"></i><span class="percent">#{female_percent}%</span></div><div class="male"><i class="icon mars"></i><span class="percent">#{male_percent}%</span></div>
          </div>
        </div>
      HTML
    end
    html.html_safe
  end

  def human_date_for(date)
    l date, format: :long
  end

  def end_date_for(project)
    if project.end_date.nil?
      "-"
    else
      l project.end_date, format: :long
    end
  end

  def end_date_full_for(project)
    html = end_date_for(project)
    if !project.end_date.nil?
      html = '<i class="icon popup calendar alternate"></i> ' + html
    end
    html.html_safe
  end

  def are_multiple_responses_allowed_for(project)
    if project.forbid_multiple_reponses
      "Interdites"
    else
      "Autorisées"
    end
  end

  def status_for(project)
    html = ""
    if project.is_closed
      html = '<span class="popup" data-html="Ce projet est <b>fermé</b> et n\'accepte pas les réponses"><span class="ui red empty circular label"></span></span>'
    else
      if project.end_date.nil?
        html = '<span class="popup" data-html="Ce projet est <b>ouvert</b> et accepte les réponses"><span class="ui green empty circular label"></span></span>'
      else
        html = '<span class="popup" data-html="Ce projet est <b>ouvert</b> et accepte les réponses"><span class="ui green empty circular label"></span></span> <i class="icon popup calendar" data-html="' + 'La <b>fermeture automatique</b> aura lieu le :<br />' + end_date_for(project) + '"></i>'
      end
    end
    html.html_safe
  end

  def status_full_for(project)
    html = ""
    if project.is_closed
      html = '<span class="ui red empty circular label"></span> <span>Ce projet est <b>fermé</b> et n\'accepte pas les réponses</span>'
    else
      if project.end_date.nil?
        html = '<span class="ui green empty circular label"></span> <span>Ce projet est <b>ouvert</b> et accepte les réponses</span>'
      else
        html = '<span class="ui green empty circular label"></span> <span>Ce projet est <b>ouvert</b> et accepte les réponses</span>'
      end
    end
    html.html_safe
  end

  def dropdown_for_order_by(order_by_possible_values, order_by_selected_value)
    hint_text = order_by_possible_values[order_by_selected_value]
    active_class = 'active selected'

    html = <<-HTML
      <div class="ui fluid projects_order selection dropdown"> Ordonner :
        <div class="text">#{hint_text}</div>
        <input type="hidden" name="order_by">
        <i class="dropdown icon"></i>
        <div class="menu">
    HTML

    order_by_possible_values.each do |data_value, description|
      if data_value == 'divider'
        html += '<div class="divider"></div>'
      else
        html += '<div class="item '
        if data_value == order_by_selected_value
          html +=active_class
        end
        html += '" data-value="' + data_value + '">' + description + '</div>'
      end
    end

    html += '</div></div>'
    html.html_safe
  end

end

app/views/projects/_edit_instructions_message.html.erb
<% if user_signed_in? && current_user == @project.user %>
  <div class="ui tiny message">
    <i class="write icon"></i><a href="#" class="show_editor_modal">Modifier la consigne</a>
  </div>
  <%= render 'editor_modal', project: @project %>
<% end %>

app/views/projects/_editor_modal.html.erb
<%= form_for(@project, :html => {:id => "instructions_editor_modal", :class => "ui modal"}) do |f| %>
  <i class="close icon"></i>
  <div class="header">Consigne affichée aux répondants</div>

  <div class="content ui text container">
    <%= f.hidden_field :instructions %>

    <trix-toolbar id="project_instructions_toolbar">
      <div class="ui icon small basic buttons toolbar">
        <button class="ui button" data-trix-attribute="bold" data-trix-key="b" title="Gras"><i class="bold icon"></i></button>
        <button class="ui button" data-trix-attribute="bullet" title="Puces"><i class="unordered list icon"></i></button>
      </div>
    </trix-toolbar>

    <trix-editor id="project_instructions_editor" input="project_instructions" toolbar="project_instructions_toolbar"></trix-editor>
  </div>
  <div class="actions">
    <button class="ui cancel primary button" type="reset">Annuler</button>
    <input type="hidden" name="redirect_back" value ="true">
    <%- I18n.with_locale(:fr) do %>
    <%= f.submit :class => "ui submit save button" %>
    <% end %>
  </div>
<% end %>

app/views/projects/_questionnaire_help_modal.html.erb
<div id="questionnaire_help_modal" class="ui modal">
  <i class="close icon"></i>
  <div class="header">Quelles différences entre les questionnaires ?</div>

  <div class="content">
    <table class="ui definition table">
      <thead>
        <tr>
          <th></th>
          <th>Description</th>
          <th nowrap>Nb. questions</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td width="20%"><%= ResponseAttrakDiff::Infos[:display_name] %></td>
          <td><%= ResponseAttrakDiff::Infos[:description].html_safe %></td>
          <td class="center aligned"><%= ResponseAttrakDiff::Infos[:number_of_questions] %></td>
        </tr>
        <tr>
          <td width="20%"><%= ResponseAttrakDiffAbridged::Infos[:display_name] %></td>
          <td>Identique mais avec moins d'items, donc plus rapide à faire passer mais moins précis.</td>
          <td class="center aligned"><%= ResponseAttrakDiffAbridged::Infos[:number_of_questions] %></td>
        </tr>
        <tr>
          <td><%= ResponseSu::Infos[:display_name] %> (<%= ResponseSu::Infos[:display_name_short] %>)</td>
          <td><%= ResponseSu::Infos[:description].html_safe %></td>
          <td class="center aligned"><%= ResponseSu::Infos[:number_of_questions] %></td>
        </tr>
        <tr>
          <td><%= ResponseDeep::Infos[:display_name] %> (<%= ResponseDeep::Infos[:display_name_short] %>)</td>
          <td><%= ResponseDeep::Infos[:description].html_safe %></td>
          <td class="center aligned"><%= ResponseDeep::Infos[:number_of_questions] %></td>
        </tr>
        <tr>
          <td><%= ResponseUmux::Infos[:display_name] %> (<%= ResponseUmux::Infos[:display_name_short] %>)</td>
          <td><%= ResponseUmux::Infos[:description].html_safe %></td>
          <td class="center aligned"><%= ResponseUmux::Infos[:number_of_questions] %></td>
        </tr>
        <tr>
          <td><%= ResponseUmuxLite::Infos[:display_name] %> (<%= ResponseUmuxLite::Infos[:display_name_short] %>)</td>
          <td><%= ResponseUmuxLite::Infos[:description].html_safe %></td>
          <td class="center aligned"><%= ResponseUmuxLite::Infos[:number_of_questions] %></td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="actions">
    <div class="ui cancel button">Fermer</div>
  </div>
</div>

app/views/projects/_questionnaire_references_modal.html.erb
<div id="questionnaire_references_modal" class="ui modal">
  <i class="close icon"></i>
  <div class="header">Références et remerciements</div>

  <div class="content">
    <p>Les questionnaires proposés et les traductions (parfois libres) sont issus de travaux de recherche et d'ouvrages dont voici les références :</p>
    <p><strong><%= ResponseAttrakDiff::Infos[:display_name] %></strong></p>
    <ul class="ui list">
      <% ResponseAttrakDiff::Infos[:bibliography].each do |s| %>
      <li><%= s.html_safe %></li>
      <% end %>
    </ul>
    <p><strong><%= ResponseDeep::Infos[:display_name] %></strong> (<%= ResponseDeep::Infos[:display_name_short] %>)</p>
    <ul class="ui list">
      <% ResponseDeep::Infos[:bibliography].each do |s| %>
      <li><%= s.html_safe %></li>
      <% end %>
    </ul>
    <p><strong><%= ResponseSu::Infos[:display_name] %></strong> (<%= ResponseSu::Infos[:display_name_short] %>)</p>
    <ul class="ui list">
      <% ResponseSu::Infos[:bibliography].each do |s| %>
      <li><%= s.html_safe %></li>
      <% end %>
    </ul>
    <p><strong><%= ResponseUmux::Infos[:display_name] %></strong> (<%= ResponseUmux::Infos[:display_name_short] %>)</p>
    <ul class="ui list">
      <% ResponseUmux::Infos[:bibliography].each do |s| %>
      <li><%= s.html_safe %></li>
      <% end %>
    </ul>
    <p><strong><%= ResponseUmuxLite::Infos[:display_name] %></strong> (<%= ResponseUmuxLite::Infos[:display_name_short] %>)</p>
    <ul class="ui list">
      <% ResponseUmuxLite::Infos[:bibliography].each do |s| %>
      <li><%= s.html_safe %></li>
      <% end %>
    </ul>
  </div>
  <div class="actions">
    <div class="ui cancel button">Fermer</div>
  </div>
</div>

app/views/projects/edit.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= project_path(@project) %>" class="ui right floated inverted button">Annuler</a>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <a href="<%= projects_path %>" class="section">Questionnaires UX</a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section"><%= @project.product_name %> - <%= @project.project_code %></h1>
  </div>
</nav>

<%= flash_messages %>

<%= render 'form', project: @project %>

app/views/projects/index.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= new_project_path %>" class="ui right floated primary button">Nouvelle évaluation</a>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section">Questionnaires UX</h1>
  </div>
</nav>

<nav class="search">
  <div class="ui grid container">
    <div class="six wide column">
      <%= form_tag(projects_path, method: "get") do %>
        <div class="ui field">
          <%= dropdown_for_order_by(@order_by_possible_values, @order_by_selected_value) %>
        </div>
      <% end %>
    </div>
  </div>
</nav>
<%= flash_messages %>

<div class="ui relaxed vertically divided middle aligned grid container">
  <% @projects.each do |project| %>
  <a href="<%= url_for project %>" class="row">
    <div class="seven wide column">
      <h2 clas="ui header">
        <%= project.product_name %> - <%= project.project_code %>
        <div class="sub header"><%= project.questionnaire_id %> (<%= project.questionnaire_language %>)</div>
      </h2>
    </div>
    <div class="four wide column">
      <%= project.product_type %>
    </div>
    <div class="two wide column">
      <%= status_for(project) %>
    </div>
    <div class="three wide right aligned column">
      <span class="ui <%= 'cream' if project.responses.count > 0 %> label">
        <%= project.responses.count.to_s + " " + "réponse".pluralize(project.responses.count) %>
      </span>
    </div>

  </a>
  <% end %>
</div>

app/views/projects/new.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= projects_path %>" class="ui right floated inverted button">Annuler</a>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <a class="section" href="<%= projects_path %>">Questionnaires UX</a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section">Nouvelle évaluation</h1>
  </div>
</nav>

<%= flash_messages %>

<%= render 'form', project: @project %>

app/views/projects/respond.html.erb
<%- I18n.with_locale(@project.questionnaire_language_code) do %>
  <% if !@project.is_closed %>
    <% if @project.forbid_multiple_reponses && @has_already_responded %>
      <div class="ui text container">
        <div class="ui segment">
        	<h2><%= t('.responded') %></h2>
          <p><%= t('.responded_details') %></p>
        </div>
        <% if user_signed_in? && current_user == @project.user %>
        <div class="ui tiny message">
          <i class="info icon"></i>Pour rappel, les réponses multiples sont interdites - <a href="<%= edit_project_path(@project) %>">modifier cette option</a>
        </div>
        <% end %>
      </div>
    <% else %>
      <% if !@showForm %>
        <%= render 'projects' + File::SEPARATOR + 'questionnaires' + File::SEPARATOR + 'introduction', project: @project %>
      <% else %>
        <%= render @form, project: @project, response: @response %>
      <% end %>
    <% end %>
  <% else %>
    <div class="ui text container">
      <div class="ui segment">
      	<h2><%= t('.closed') %></h2>
        <p><%= t('.closed_details') %></p>
      </div>
    </div>
  <% end %>
<% end %>

app/views/projects/response_saved.html.erb
<%- I18n.with_locale(@locale) do %>
<div class="ui text container">
  <div class="ui segment">
  	<h2><%= t('.thanks') %></h2>
    <p><%= t('.thanks_details') %></p>
  </div>
</div>
<% end %>

app/views/projects/show.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= edit_project_path(@project) %>" class="ui right floated primary button">Modifier</a>
    <% if !@project.is_closed %>
    <a href="<%= close_project_path(@project) %>" class="ui right floated left labeled button"><span class="ui green right pointing label">Ouvert</span><span class="ui inverted button">Fermer le projet</span></a>
    <% else %>
    <a href="<%= open_project_path(@project) %>" class="ui right floated left labeled button"><span class="ui red right pointing label">Fermé</span><span class="ui inverted button">Réouvrir le projet</span></a>
    <% end %>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <a href="<%= projects_path %>" class="section">Questionnaires UX</a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section"><%= @project.product_name %> - <%= @project.project_code %></h1>
  </div>
</nav>

<%= flash_messages %>

<div class="ui container">
  <div class="ui pointing secondary menu">
    <a class="item <%= "active" unless @project.has_responses? || @back_to_responses %>" data-tab="description">Description</a>
    <a class="item <%= "active" if @project.has_responses? && !@back_to_responses %>" data-tab="results">Résultats</a>
    <a class="item <%= "active" if @back_to_responses %>" data-tab="responses">Réponses</a>
  </div>
  <div class="ui tab <%= "active" unless @project.has_responses? || @back_to_responses %>" data-tab="description">

    <table class="ui very basic table">
      <tbody>
        <tr>
          <td width="20%" nowrap>Questionnaire :</td>
          <td><%= @project.questionnaire_id %> (<%= @project.questionnaire_language %>) - <a href="#" class="show_editor_modal">consulter et modifier la consigne</a></td>
        </tr>
        <tr>
          <td nowrap>Type de produit :</td>
          <td><%= @project.product_type %></td>
        </tr>
        <tr>
          <td nowrap>Statut :</td>
          <td><%= status_full_for(@project) %></td>
        </tr>
        <tr>
          <td nowrap>Lien public pour répondre :</td>
          <td><%= link_to project_public_respond_url(@project.uri_token), project_public_respond_path(@project.uri_token) %>
        </tr>
        <% if @project.ask_user_summary || @project.ask_user_ideas %>
        <tr>
          <td nowrap>Questions ouvertes :</td>
          <td>
            <div class="ui list">
              <% if @project.ask_user_summary %><div class="item"><i class="check green icon"></i>Demander l'avis général sur le produit</div><% end %>
              <% if @project.ask_user_ideas %><div class="item"><i class="check green icon"></i>Demander des suggestions d'idées</div><% end %>
            </div>
          </td>
        </tr>
        <% end %>
        <% if @project.ask_user_age || @project.ask_user_gender || @project.ask_user_occupation || @project.ask_user_first_use_date || @project.ask_user_usage_frequency %>
        <tr>
          <td nowrap>Qualification des répondants :</td>
          <td>
            <div class="ui list">
              <% if @project.ask_user_age %><div class="item"><i class="check green icon"></i>Âge</div><% end %>
              <% if @project.ask_user_gender %><div class="item"><i class="check green icon"></i>Sexe</div><% end %>
              <% if @project.ask_user_occupation %><div class="item"><i class="check green icon"></i>Métier (ou occupation)</div><% end %>
              <% if @project.ask_user_first_use_date %><div class="item"><i class="check green icon"></i>Date de première utilisation du produit ou service</div><% end %>
              <% if @project.ask_user_usage_frequency %><div class="item"><i class="check green icon"></i>Fréquence d'utilisation mensuelle du produit ou service</div><% end %>
            </div>
          </td>
        </tr>
        <% end %>
        <% if @project.ask_user_group %>
        <tr>
          <td nowrap>Groupes d'utilisateurs :</td>
          <td>
            <div class="ui list">
              <div class="item"><i class="check green circle icon"></i>Demander aux répondants de choisir leur groupe</div>
            </div>
          </td>
        </tr>
        <% end %>
        <tr>
          <td nowrap>Date de fin de l'évaluation :</td>
          <td><%= end_date_full_for(@project) %></td>
        </tr>
        <tr>
          <td nowrap>Réponses multiples :</td>
          <td><%= are_multiple_responses_allowed_for(@project) %></td>
        </tr>
      </tbody>
    </table>
  </div>

    <div class="ui tab <%= "active" if @project.has_responses? && !@back_to_responses %>" data-tab="results">
      <%= render 'projects' + File::SEPARATOR + 'results' + File::SEPARATOR + @project.questionnaire_id_clean %>
    </div>

    <div class="ui tab <%= "active" if @back_to_responses %>" data-tab="responses" id="responsesTab">
      <%= render 'projects' + File::SEPARATOR + 'responses' + File::SEPARATOR + @project.questionnaire_id_clean %>
    </div>

</div>

<%= render 'editor_modal', project: @project %>