config/routes.rb
Rails.application.routes.draw do
  resources :response_umux_lites
  resources :response_umuxes
  resources :app_notifications
  resources :response_sus
  resources :response_attrak_diffs
  resources :response_attrak_diff_abridgeds
  resources :response_deeps
  resources :projects
  devise_for :users
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/index'
  get 'admin/project/:id', to: 'admin#project', as: 'admin_project'

  get 'welcome/index'
  get 'projects/index'

  get 'projects/:id/close', to: 'projects#close', as: 'close_project'
  get 'projects/:id/open', to: 'projects#open', as: 'open_project'

  get 'response_sus/recover/:id', to: 'response_sus#recover', as: 'recover_response_sus'
  get 'response_attrak_diffs/recover/:id', to: 'response_attrak_diffs#recover', as: 'recover_response_attrak_diffs'
  get 'response_attrak_diff_abridgeds/recover/:id', to: 'response_attrak_diff_abridgeds#recover', as: 'recover_response_attrak_diff_abridgeds'
  get 'response_deeps/recover/:id', to: 'response_deeps#recover', as: 'recover_response_deeps'
  get 'response_umuxes/recover/:id', to: 'response_umuxes#recover', as: 'recover_response_umuxes'
  get 'response_umux_lites/recover/:id', to: 'response_umux_lites#recover', as: 'recover_response_umux_lites'

  get 'app_notifications/mark_as_read/:id', to: 'app_notifications#mark_as_read', as: 'mark_notification_as_read'

  get 'sample_sizes/usability_problems'
  get 'timer/index'

  get 'r/success/:locale', to: 'projects#response_saved', as: 'project_public_response_saved'
  get 'r/:uri_token', to: 'projects#respond', as: 'project_public_respond'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  before_action :authenticate_user!, except: [:respond, :response_saved]
  before_action :set_project, only: [:show, :edit, :update, :close, :open, :destroy]
  before_action :load_project_data, only: [:show]

  # GET /projects
  # GET /projects.json
  def index
    default = 'date_desc'
    whitelist = ['name_asc', 'name_desc', 'date_asc', 'date_desc']
    @order_by_possible_values = {
      'date_desc' => 'du plus récent au plus ancien',
      'date_asc'  => 'du plus ancien au plus récent',
      'divider'   => '',
      'name_asc'  => 'de A à Z',
      'name_desc'  => 'de Z à A'
    }
    @order_by_selected_value = default
    @projects = current_user.projects.order(created_at: :desc)
    if (params.has_key?(:order_by) && whitelist.include?(params[:order_by]))
      @order_by_selected_value = params[:order_by]
      cookies[:order_projects_by] = params[:order_by]
    else
      if cookies[:order_projects_by] && whitelist.include?(cookies[:order_projects_by])
        @order_by_selected_value = cookies[:order_projects_by]
      end
    end

    case @order_by_selected_value
    when "name_asc"
      @projects = current_user.projects.order(product_name: :asc)
    when "name_desc"
      @projects = current_user.projects.order(product_name: :desc)
    when "date_asc"
      @projects = current_user.projects.order(created_at: :asc)
    when "date_desc"
      @projects = current_user.projects.order(created_at: :desc)
    end

  end

  # GET /projects/1
  # GET /projects/1.csv
  def show
    @show_variability = false
    if cookies[:show_variability] && cookies[:show_variability].to_i > 0
      @show_variability = true
    end
    @ci_level = cookies[:ci_level] || '95%'
    @ci_level_hash_key = 'ci_' + @ci_level[0..1]
    @ci_level_hash_key = @ci_level_hash_key.to_sym

    @back_to_responses = session["back_to_responses"]
    session["back_to_responses"] = nil

    filename = "[Questionnaire UX] - " + @project.product_name + "-" + @project.project_code + " (" + @project.questionnaire_id + ") - #{Date.today}"
    respond_to do |format|
      format.html
      #format.csv { send_data @project.responses.to_csv, filename: filename + ".csv" }
      format.xlsx { response.headers['Content-Disposition'] = 'attachment; filename="' + filename + '.xlsx"' }
    end
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # GET /projects/1/close
  def close
    @project.is_closed = true
    @project.save
    respond_to do |format|
      format.html { redirect_back fallback_location: @project }
    end
  end

  # GET /projects/1/open
  def open
    message = nil
    @project.is_closed = false
    if @project.should_get_closed
      @project.end_date = nil
      message = "Le projet a bien été réouvert et la date de fin a été supprimée."
    end
    @project.save
    respond_to do |format|
      format.html { redirect_back fallback_location: @project, notice: message }
    end
  end

  # GET /r/1
  def respond
    @project = Project.find_by uri_token: params[:uri_token]

    #Updates project status if needed
    if @project.should_get_closed
      @project.is_closed = true
      @project.save
    end

    @showForm = false
    @form = ''
    @has_already_responded = has_already_responded(@project)

    if (params.has_key?(:step))
      case @project.questionnaire_id_clean
      when "attrakdiff"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseAttrakDiff.new
        else
        end
      when "attrakdiff_abrege"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseAttrakDiffAbridged.new
        else
        end
      when "system_usability_scale"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseSu.new
        else
        end
      when "deep"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseDeep.new
        else
        end
      when "umux"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseUmux.new
        else
        end
      when "umux_lite"
        case params[:step]
        when "1"
          @showForm = true
          @form = @project.questionnaire_template + "_" + "step" + params[:step]
          @response = ResponseUmuxLite.new
        else
        end
      end
    end
    render layout: "public_response"
  end

  # GET /r/success/fr
  # GET /r/success.json/fr
  def response_saved
    @locale = params[:locale]
    @locale = I18n.default_locale unless I18n.locale_available? @locale
    render layout: "public_response"
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    @project.user = current_user

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if params["redirect_back"] === "true"
      redirect_back = true
    else
      redirect_back = false
    end

    respond_to do |format|
      if @project.update(project_params)
        if redirect_back
          format.html { redirect_back fallback_location: @project, notice: "La modification a bien été enregistrée." }
        else
          format.html { redirect_to @project, notice: 'La modification a bien été enregistrée.' }
        end
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy_fully!
    #@project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Le projet d'évaluation a bien été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:questionnaire_id, :questionnaire_language, :product_type, :product_name, :project_code, :instructions, :end_date, :uri_token, :forbid_multiple_reponses, :ask_user_ideas, :ask_user_summary, :ask_user_age, :ask_user_gender, :ask_user_occupation, :ask_user_first_use_date, :ask_user_group, :ask_user_usage_frequency)
    end

end

app/helpers/projects_helper.rb
module ProjectsHelper

  def gender_icon_for(gender)
    html = ''
    if gender == 1
      html = '<i class="icon venus"></i>'
    elsif gender == 2
      html = '<i class="icon mars"></i>'
    end
    html.html_safe
  end

  def gender_graph_stats_for(users_gender_mean)
    html = '-'
    if users_gender_mean > 0
      female_width = ((2 - users_gender_mean)*100).round
      female_percent = ((2 - users_gender_mean)*100).round(2)
      male_width = ((users_gender_mean - 1)*100).round
      male_percent = ((users_gender_mean - 1)*100).round(2)
      split_width = 2
      if female_width < 2
        female_width = 2
        male_width = 96
      elsif male_width < 2
        male_width = 2
        female_width = 96
      else
        female_width = female_width - 1
        male_width = male_width - 1
      end
      html = <<-HTML
        <div class="gender">
          <div class="data">
            <div class="female bar" style="width:#{female_width}%"></div><div class="split bar" style="width:#{split_width}%"></div><div class="male bar" style="width:#{male_width}%"></div>
          </div>
          <div class="label">
            <div class="female"><i class="icon venus"></i><span class="percent">#{female_percent}%</span></div><div class="male"><i class="icon mars"></i><span class="percent">#{male_percent}%</span></div>
          </div>
        </div>
      HTML
    end
    html.html_safe
  end

  def human_date_for(date)
    l date, format: :long
  end

  def end_date_for(project)
    if project.end_date.nil?
      "-"
    else
      l project.end_date, format: :long
    end
  end

  def end_date_full_for(project)
    html = end_date_for(project)
    if !project.end_date.nil?
      html = '<i class="icon popup calendar alternate"></i> ' + html
    end
    html.html_safe
  end

  def are_multiple_responses_allowed_for(project)
    if project.forbid_multiple_reponses
      "Interdites"
    else
      "Autorisées"
    end
  end

  def status_for(project)
    html = ""
    if project.is_closed
      html = '<span class="popup" data-html="Ce projet est <b>fermé</b> et n\'accepte pas les réponses"><span class="ui red empty circular label"></span></span>'
    else
      if project.end_date.nil?
        html = '<span class="popup" data-html="Ce projet est <b>ouvert</b> et accepte les réponses"><span class="ui green empty circular label"></span></span>'
      else
        html = '<span class="popup" data-html="Ce projet est <b>ouvert</b> et accepte les réponses"><span class="ui green empty circular label"></span></span> <i class="icon popup calendar" data-html="' + 'La <b>fermeture automatique</b> aura lieu le :<br />' + end_date_for(project) + '"></i>'
      end
    end
    html.html_safe
  end

  def status_full_for(project)
    html = ""
    if project.is_closed
      html = '<span class="ui red empty circular label"></span> <span>Ce projet est <b>fermé</b> et n\'accepte pas les réponses</span>'
    else
      if project.end_date.nil?
        html = '<span class="ui green empty circular label"></span> <span>Ce projet est <b>ouvert</b> et accepte les réponses</span>'
      else
        html = '<span class="ui green empty circular label"></span> <span>Ce projet est <b>ouvert</b> et accepte les réponses</span>'
      end
    end
    html.html_safe
  end

  def dropdown_for_order_by(order_by_possible_values, order_by_selected_value)
    hint_text = order_by_possible_values[order_by_selected_value]
    active_class = 'active selected'

    html = <<-HTML
      <div class="ui fluid projects_order selection dropdown"> Ordonner :
        <div class="text">#{hint_text}</div>
        <input type="hidden" name="order_by">
        <i class="dropdown icon"></i>
        <div class="menu">
    HTML

    order_by_possible_values.each do |data_value, description|
      if data_value == 'divider'
        html += '<div class="divider"></div>'
      else
        html += '<div class="item '
        if data_value == order_by_selected_value
          html +=active_class
        end
        html += '" data-value="' + data_value + '">' + description + '</div>'
      end
    end

    html += '</div></div>'
    html.html_safe
  end

end

app/views/projects/responses/_attrakdiff.html.erb
<a href="<%= url_for project_path(@project, format: "xlsx") %>" class="ui button <%= 'disabled' if !@project.has_responses? %>">Télécharger les données brutes (.xlsx)</a>
<%
  respondent_cols = 1
  respondent_cols += 1 if @project.ask_user_gender
  respondent_cols += 1 if @project.ask_user_age
  rowspan = 1
  rowspan += 1 if respondent_cols > 1
%>

<%= render 'projects' + File::SEPARATOR + 'responses' + File::SEPARATOR + 'too_many_responses', project: @project %>

<table class="ui small compact celled table">
  <thead>
    <tr>
      <th class="collapsing" colspan="<%= respondent_cols %>">Répondant</th>
      <th rowspan="<%= rowspan %>">Attractivité Globale</th>
      <th rowspan="<%= rowspan %>">Qualité Pragmatique</th>
      <th rowspan="<%= rowspan %>">Qualité Hédonique</th>
      <th rowspan="<%= rowspan %>">Date et heure (Paris)</th>
      <th class="collapsing" rowspan="<%= rowspan %>">Actions</th>
    </tr>
    <% if respondent_cols > 1 %>
    <tr class="sub-header">
      <th>#</th>
      <% if @project.ask_user_gender %><th>Sexe</th><% end %>
      <% if @project.ask_user_age %><th>Âge</th><% end %>
    </tr>
    <% end %>
  </thead>
  <tbody>
    <%
      i = 0
      if @project.responses.count >= 40
        i = @project.responses.count - 40
      end
      @project.responses.order("created_at asc").last(40).each do |response|
        i = i + 1
        scores = Stats::AttrakDiff::average_scores(response)
    %>
    <tr>
      <td><%= i %></td>
      <% if @project.ask_user_gender %><td><%= gender_icon_for(response.gender) %></td><% end %>
      <% if @project.ask_user_age %><td><%= human_age_for(response.age) %></td><% end %>
      <td><%= scores[:ATT][:mean] %></td>
      <td><%= scores[:QP][:mean] %></td>
      <td><%= scores[:QH][:mean] %></td>
      <td class="collapsing"><%= human_date_for(response.created_at) %></td>
      <td class="action"><%= link_to "Supprimer", response, method: :delete %></td>
    </tr>
    <% end %>
    <%
      @project.responses.only_deleted.order("created_at asc").each do |response|
        scores = Stats::AttrakDiff::average_scores(response)
    %>
    <tr class="deleted">
      <td>-</td>
      <% if @project.ask_user_gender %><td><%= gender_icon_for(response.gender) %></td><% end %>
      <% if @project.ask_user_age %><td><%= human_age_for(response.age) %></td><% end %>
      <td><%= scores[:ATT][:mean] %></td>
      <td><%= scores[:QP][:mean] %></td>
      <td><%= scores[:QH][:mean] %></td>
      <td class="collapsing"><%= human_date_for(response.created_at) %></td>
      <td class="action"><%= link_to "Récupérer", recover_response_attrak_diffs_url(response) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th>N = <%= @project.responses.count %></th>
      <% if @project.ask_user_gender %><th class="collapsing"><%= gender_graph_stats_for(@users_stats[:gender][:mean]) %></th><% end %>
      <% if @project.ask_user_age %><th class="collapsing"><%= @users_stats[:age][:mean] %> <small>(σ = <%= @users_stats[:age][:sd] %>)</small></th><% end %>
      <th><%= @attrakdiff_average_scores[:ATT][:mean] %> <small>(σ = <%= @attrakdiff_average_scores[:ATT][:sd] %>)</small></th>
      <th><%= @attrakdiff_average_scores[:QP][:mean] %> <small>(σ = <%= @attrakdiff_average_scores[:QP][:sd] %>)</small></th>
      <th><%= @attrakdiff_average_scores[:QH][:mean] %> <small>(σ = <%= @attrakdiff_average_scores[:QH][:sd] %>)</small></th>
      <th colspan="2"></th>
    </tr>
  </tfoot>
</table>

app/views/projects/responses/_attrakdiff_abrege.html.erb
<a href="<%= url_for project_path(@project, format: "xlsx") %>" class="ui button <%= 'disabled' if !@project.has_responses? %>">Télécharger les données brutes (.xlsx)</a>
<%
  respondent_cols = 1
  respondent_cols += 1 if @project.ask_user_gender
  respondent_cols += 1 if @project.ask_user_age
  rowspan = 1
  rowspan += 1 if respondent_cols > 1
%>

<%= render 'projects' + File::SEPARATOR + 'responses' + File::SEPARATOR + 'too_many_responses', project: @project %>

<table class="ui small compact celled structured table">
  <thead>
    <tr>
      <th class="collapsing" colspan="<%= respondent_cols %>">Répondant</th>
      <th rowspan="<%= rowspan %>">Attractivité Globale</th>
      <th rowspan="<%= rowspan %>">Qualité Pragmatique</th>
      <th rowspan="<%= rowspan %>">Qualité Hédonique</th>
      <th rowspan="<%= rowspan %>">Date et heure (Paris)</th>
      <th class="collapsing" rowspan="<%= rowspan %>">Actions</th>
    </tr>
    <% if respondent_cols > 1 %>
    <tr class="sub-header">
      <th>#</th>
      <% if @project.ask_user_gender %><th>Sexe</th><% end %>
      <% if @project.ask_user_age %><th>Âge</th><% end %>
    </tr>
    <% end %>
  </thead>
  </thead>
  <tbody>
    <%
      i = 0
      if @project.responses.count >= 40
        i = @project.responses.count - 40
      end
      @project.responses.order("created_at asc").last(40).each do |response|
        i = i + 1
        scores = Stats::AttrakDiff::average_scores(response, true)
    %>
    <tr>
      <td><%= i %></td>
      <% if @project.ask_user_gender %><td><%= gender_icon_for(response.gender) %></td><% end %>
      <% if @project.ask_user_age %><td><%= human_age_for(response.age) %></td><% end %>
      <td><%= scores[:ATT][:mean] %></td>
      <td><%= scores[:QP][:mean] %></td>
      <td><%= scores[:QH][:mean] %></td>
      <td class="collapsing"><%= human_date_for(response.created_at) %></td>
      <td class="action"><%= link_to "Supprimer", response, method: :delete %></td>
    </tr>
    <% end %>
    <%
      @project.responses.only_deleted.order("created_at asc").each do |response|
        scores = Stats::AttrakDiff::average_scores(response, true)
    %>
    <tr class="deleted">
      <td>-</td>
      <% if @project.ask_user_gender %><td><%= gender_icon_for(response.gender) %></td><% end %>
      <% if @project.ask_user_age %><td><%= human_age_for(response.age) %></td><% end %>
      <td><%= scores[:ATT][:mean] %></td>
      <td><%= scores[:QP][:mean] %></td>
      <td><%= scores[:QH][:mean] %></td>
      <td class="collapsing"><%= human_date_for(response.created_at) %></td>
      <td class="action"><%= link_to "Récupérer", recover_response_attrak_diff_abridgeds_url(response) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th>N = <%= @project.responses.count %></th>
      <% if @project.ask_user_gender %><th class="collapsing"><%= gender_graph_stats_for(@users_stats[:gender][:mean]) %></th><% end %>
      <% if @project.ask_user_age %><th class="collapsing"><%= @users_stats[:age][:mean] %> <small>(σ = <%= @users_stats[:age][:sd] %>)</small></th><% end %>
      <th><%= @attrakdiff_average_scores[:ATT][:mean] %> <small>(σ = <%= @attrakdiff_average_scores[:ATT][:sd] %>)</small></th>
      <th><%= @attrakdiff_average_scores[:QP][:mean] %> <small>(σ = <%= @attrakdiff_average_scores[:QP][:sd] %>)</small></th>
      <th><%= @attrakdiff_average_scores[:QH][:mean] %> <small>(σ = <%= @attrakdiff_average_scores[:QH][:sd] %>)</small></th>
      <th colspan="2"></th>
    </tr>
  </tfoot>
</table>

app/views/projects/responses/_deep.html.erb
<a href="<%= url_for project_path(@project, format: "xlsx") %>" class="ui button <%= 'disabled' if !@project.has_responses? %>">Télécharger les données brutes (.xlsx)</a>
<%
  respondent_cols = 1
  respondent_cols += 1 if @project.ask_user_gender
  respondent_cols += 1 if @project.ask_user_age
  rowspan = 1
  rowspan += 1 if respondent_cols > 1
%>

<%= render 'projects' + File::SEPARATOR + 'responses' + File::SEPARATOR + 'too_many_responses', project: @project %>

<table class="ui small compact celled table">
  <thead>
    <tr>
      <th class="collapsing" colspan="<%= respondent_cols %>">Répondant</th>
      <th rowspan="<%= rowspan %>"><%= ResponseDeep::G1_label[I18n.locale].partition(" ").first %></th>
      <th rowspan="<%= rowspan %>"><%= ResponseDeep::G2_label[I18n.locale].partition(" ").first %></th>
      <th rowspan="<%= rowspan %>"><%= ResponseDeep::G3_label[I18n.locale].partition(" ").first %></th>
      <th rowspan="<%= rowspan %>"><%= ResponseDeep::G4_label[I18n.locale].partition(" ").first %></th>
      <th rowspan="<%= rowspan %>"><%= ResponseDeep::G5_label[I18n.locale].partition(" ").first %></th>
      <th rowspan="<%= rowspan %>"><%= ResponseDeep::G6_label[I18n.locale].partition(" ").first %></th>
      <th rowspan="<%= rowspan %>">Date et heure (Paris)</th>
      <th class="collapsing" rowspan="<%= rowspan %>">Actions</th>
    </tr>
    <% if respondent_cols > 1 %>
    <tr class="sub-header">
      <th>#</th>
      <% if @project.ask_user_gender %><th>Sexe</th><% end %>
      <% if @project.ask_user_age %><th>Âge</th><% end %>
    </tr>
    <% end %>
  </thead>
  <tbody>
    <%
      i = 0
      if @project.responses.count >= 40
        i = @project.responses.count - 40
      end
      @project.responses.order("created_at asc").last(40).each do |response|
        i = i + 1
        scores = Stats::Deep::average_scores(response)
    %>
    <tr>
      <td><%= i %></td>
      <% if @project.ask_user_gender %><td><%= gender_icon_for(response.gender) %></td><% end %>
      <% if @project.ask_user_age %><td><%= human_age_for(response.age) %></td><% end %>
      <td><%= scores[:G1][:mean] %></td>
      <td><%= scores[:G2][:mean] %></td>
      <td><%= scores[:G3][:mean] %></td>
      <td><%= scores[:G4][:mean] %></td>
      <td><%= scores[:G5][:mean] %></td>
      <td><%= scores[:G6][:mean] %></td>
      <td class="collapsing"><%= human_date_for(response.created_at) %></td>
      <td class="action"><%= link_to "Supprimer", response, method: :delete %></td>
    </tr>
    <% end %>
    <%
      @project.responses.only_deleted.order("created_at asc").each do |response|
        scores = Stats::Deep::average_scores(response)
    %>
    <tr class="deleted">
      <td>-</td>
      <% if @project.ask_user_gender %><td><%= gender_icon_for(response.gender) %></td><% end %>
      <% if @project.ask_user_age %><td><%= human_age_for(response.age) %></td><% end %>
      <td><%= scores[:G1][:mean] %></td>
      <td><%= scores[:G2][:mean] %></td>
      <td><%= scores[:G3][:mean] %></td>
      <td><%= scores[:G4][:mean] %></td>
      <td><%= scores[:G5][:mean] %></td>
      <td><%= scores[:G6][:mean] %></td>
      <td class="collapsing"><%= human_date_for(response.created_at) %></td>
      <td class="action"><%= link_to "Récupérer", recover_response_deeps_url(response) %></td>
    </tr>
    <% end %>
  </tbody>
  <tfoot class="full-width">
    <tr>
      <th>N = <%= @project.responses.count %></th>
      <% if @project.ask_user_gender %><th class="collapsing"><%= gender_graph_stats_for(@users_stats[:gender][:mean]) %></th><% end %>
      <% if @project.ask_user_age %><th class="collapsing"><%= @users_stats[:age][:mean] %> <small>(σ = <%= @users_stats[:age][:sd] %>)</small></th><% end %>
      <th><%= @deep_scores[:G1][:mean] %> <small>(σ = <%= @deep_scores[:G1][:sd] %>)</small></th>
      <th><%= @deep_scores[:G2][:mean] %> <small>(σ = <%= @deep_scores[:G2][:sd] %>)</small></th>
      <th><%= @deep_scores[:G3][:mean] %> <small>(σ = <%= @deep_scores[:G3][:sd] %>)</small></th>
      <th><%= @deep_scores[:G4][:mean] %> <small>(σ = <%= @deep_scores[:G4][:sd] %>)</small></th>
      <th><%= @deep_scores[:G5][:mean] %> <small>(σ = <%= @deep_scores[:G5][:sd] %>)</small></th>
      <th><%= @deep_scores[:G6][:mean] %> <small>(σ = <%= @deep_scores[:G6][:sd] %>)</small></th>
      <th colspan="2"></th>
    </tr>
  </tfoot>
</table>

app/views/projects/responses/_too_many_responses.html.erb
<% if @project.responses.count >= 40 %>
<div class="ui warning message">
  <div class="header">
    Beaucoup de données ...
  </div>
  <ul class="list">
    <li>Votre questionnaire contient <span class="ui cream horizontal label"><%= @project.responses.count %> réponses</span></li>
    <li>Pour réduire le temps de chargement de cette page, nous affichons seulement les <strong>40 réponses les plus récentes</strong>.</li>
    <li>Pour voir l'intégralité des réponses, téléchargez les données brutes (fichier XLS).</li>
  </ul>
</div>
<% end %>