config/routes.rb
Rails.application.routes.draw do
  resources :response_umux_lites
  resources :response_umuxes
  resources :app_notifications
  resources :response_sus
  resources :response_attrak_diffs
  resources :response_attrak_diff_abridgeds
  resources :response_deeps
  resources :projects
  devise_for :users
  get 'admin', to: 'admin#index', as: 'admin'
  get 'admin/index'
  get 'admin/project/:id', to: 'admin#project', as: 'admin_project'

  get 'welcome/index'
  get 'projects/index'

  get 'projects/:id/close', to: 'projects#close', as: 'close_project'
  get 'projects/:id/open', to: 'projects#open', as: 'open_project'

  get 'response_sus/recover/:id', to: 'response_sus#recover', as: 'recover_response_sus'
  get 'response_attrak_diffs/recover/:id', to: 'response_attrak_diffs#recover', as: 'recover_response_attrak_diffs'
  get 'response_attrak_diff_abridgeds/recover/:id', to: 'response_attrak_diff_abridgeds#recover', as: 'recover_response_attrak_diff_abridgeds'
  get 'response_deeps/recover/:id', to: 'response_deeps#recover', as: 'recover_response_deeps'
  get 'response_umuxes/recover/:id', to: 'response_umuxes#recover', as: 'recover_response_umuxes'
  get 'response_umux_lites/recover/:id', to: 'response_umux_lites#recover', as: 'recover_response_umux_lites'

  get 'app_notifications/mark_as_read/:id', to: 'app_notifications#mark_as_read', as: 'mark_notification_as_read'

  get 'sample_sizes/usability_problems'
  get 'timer/index'

  get 'r/success/:locale', to: 'projects#response_saved', as: 'project_public_response_saved'
  get 'r/:uri_token', to: 'projects#respond', as: 'project_public_respond'

  root 'welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/app_notification.rb
class AppNotification < ApplicationRecord
  has_many :read_app_notifications, dependent: :destroy

  validates_presence_of :date, :notification_type, :title, :content

  def read_count
    read_app_notifications.count
  end

  def should_have_read_count
    User.where("created_at <= :notification_date", {notification_date: date}).count
  end

end

app/controllers/app_notifications_controller.rb
class AppNotificationsController < ApplicationController
  before_action :set_app_notification, only: [:mark_as_read, :show, :edit, :update, :destroy]

  before_action :authenticate_user!
  before_action :authenticate_admin_user, only: [:index, :show, :new, :edit, :create, :update, :destroy]

  # GET /app_notifications/mark_as_read/1
  # GET /app_notifications/mark_as_read/1.json
  def mark_as_read
    @read_app_notification = ReadAppNotification.new()
    @read_app_notification.app_notification = @app_notification
    @read_app_notification.user = current_user
    respond_to do |format|
      if @read_app_notification.save
        format.html { redirect_back fallback_location: root_url }
        format.json { render :mark_as_read, status: :created }
      else
        format.html { render :new }
        format.json { render json: @read_app_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /app_notifications
  # GET /app_notifications.json
  def index
    @app_notifications = AppNotification.all.order(date: :desc)
  end

  # GET /app_notifications/1
  # GET /app_notifications/1.json
  def show
    redirect_to app_notifications_url, notice: 'Desactivé...'
  end

  # GET /app_notifications/new
  def new
    @app_notification = AppNotification.new
  end

  # GET /app_notifications/1/edit
  def edit
  end

  # POST /app_notifications
  # POST /app_notifications.json
  def create
    @app_notification = AppNotification.new(app_notification_params)

    respond_to do |format|
      if @app_notification.save
        format.html { redirect_to app_notifications_url, notice: 'App notification was successfully created.' }
      else
        format.html { render :new }
        format.json { render json: @app_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /app_notifications/1
  # PATCH/PUT /app_notifications/1.json
  def update
    respond_to do |format|
      if @app_notification.update(app_notification_params)
        format.html { redirect_to app_notifications_url, notice: 'App notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @app_notification }
      else
        format.html { render :edit }
        format.json { render json: @app_notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /app_notifications/1
  # DELETE /app_notifications/1.json
  def destroy
    @app_notification.destroy
    respond_to do |format|
      format.html { redirect_to app_notifications_url, notice: 'App notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_app_notification
      @app_notification = AppNotification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def app_notification_params
      params.require(:app_notification).permit(:date, :notification_type, :title, :content)
    end
end

app/helpers/app_notifications_helper.rb
module AppNotificationsHelper
end

app/views/app_notifications/_form.html.erb
<%= form_error_messages_for(app_notification) %>

<div class="ui container">
  <%= form_for(app_notification, :html => {:class => "ui large form evaluation-project"}) do |f| %>
  <div class="ui stacked segment grid">

    <div class="row no-padding field">
      <div class="five wide column"><%= f.label :date, 'Date :' %></div>
      <div class="eleven wide column">

        <div class="ui date calendar">
          <div class="ui left icon action input">
            <i class="calendar icon"></i>
            <input type="text" placeholder="Date" value="<%= app_notification.date %>">
            <div class="ui icon clear-date basic button">
              <i class="close icon"></i>
            </div>
          </div>
        </div>
        <input type="hidden" name="app_notification[date]" id="app_notification_date" value="<%= app_notification.date %>">
      </div>
    </div>

    <div class="row no-padding field">
      <div class="five wide column"><%= f.label :notification_type, 'Type de notification :' %></div>
      <div class="eleven wide column"><%= f.text_field :notification_type, :placeholder => "Ex. gift, warning sign, etc." %></div>
    </div>

    <div class="row no-padding field">
      <div class="five wide column"><%= f.label :title, 'Titre :' %></div>
      <div class="eleven wide column"><%= f.text_field :title, :placeholder => "Ex. Consignes dynamiques pour SUS" %></div>
    </div>

    <div class="row no-padding field">
      <div class="five wide column"><%= f.label :content, 'Contenu :' %></div>
      <div class="eleven wide column">
        <div class="content ui text container">
          <%= f.hidden_field :content %>

          <trix-toolbar id="app_notification_content_toolbar">
            <div class="ui icon small basic buttons toolbar">
              <button class="ui button" data-trix-attribute="bold" data-trix-key="b" title="Gras"><i class="bold icon"></i></button>
              <button class="ui button" data-trix-attribute="italic" data-trix-key="i" title="Italique"><i class="italic icon"></i></button>
              <button class="ui button" data-trix-attribute="bullet" title="Puces"><i class="unordered list icon"></i></button>
            </div>
          </trix-toolbar>

          <trix-editor id="app_notification_content_editor" input="app_notification_content" toolbar="app_notification_content_toolbar"></trix-editor>
        </div>
      </div>
    </div>



    <div class="row no-padding field">
      <div class="five wide column"></div>
      <div class="eleven wide column"><%= f.submit :class => "ui large submit button" %></div>
    </div>

  </div>
  <% end %>
</div>

app/views/app_notifications/edit.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= app_notifications_path %>" class="ui right floated inverted button">Annuler</a>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <a href="<%= app_notifications_path %>" class="section">Notifications</a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section"><%= @app_notification.title %> (<%= l @app_notification.date, format: :long %>)</h1>
  </div>
</nav>

<%= flash_messages %>

<%= render 'form', app_notification: @app_notification %>

app/views/app_notifications/index.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= new_app_notification_path %>" class="ui right floated primary button">Nouvelle notification</a>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section">Notifications</h1>
  </div>
</nav>

<%= flash_messages %>

<div class="ui container">

  <h2 class="ui header">Liste des notifications du service</h2>

  <table class="ui table">
    <thead>
      <tr>
        <th>Date</th>
        <th>Type</th>
        <th>Titre</th>
        <th>Ratio lecture</th>
        <th colspan="2"></th>
      </tr>
    </thead>

    <tbody>
      <% @app_notifications.each do |app_notification|
        read_count = app_notification.read_count
        should_have_read_count = app_notification.should_have_read_count
        ratio = (((read_count + 0.00)/(should_have_read_count + 0.00)) * 100).round(2)
      %>
        <tr>
          <td><%= l app_notification.date, format: :custom  %></td>
          <td><%= app_notification.notification_type %></td>
          <td><%= app_notification.title %></td>
          <td><%= ratio %>% <small>(<%= read_count %>/<%= should_have_read_count %>)</small></td>
          <td><%= link_to 'Modifier', edit_app_notification_path(app_notification) %></td>
          <td><%= button_to 'Supprimer', app_notification, method: :delete, :class => "ui red button", data: { modalconfirm: t('.are_you_sure') } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

</div>

app/views/app_notifications/new.html.erb
<nav class="bc">
  <div class="ui large breadcrumb container">
    <a href="<%= app_notifications_path %>" class="ui right floated inverted button">Annuler</a>
    <a class="section" href="<%= root_path %>"><%= root_path_name %></a>
    <i class="right chevron icon divider"></i>
    <a href="<%= app_notifications_path %>" class="section">Notifications</a>
    <i class="right chevron icon divider"></i>
    <h1 class="active section">Nouvelle notification</h1>
  </div>
</nav>

<%= flash_messages %>

<%= render 'form', app_notification: @app_notification %>

app/views/app_notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @app_notification.date %>
</p>

<p>
  <strong>Notification type:</strong>
  <%= @app_notification.notification_type %>
</p>

<p>
  <strong>Title:</strong>
  <%= @app_notification.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @app_notification.content %>
</p>

<%= link_to 'Edit', edit_app_notification_path(@app_notification) %> |
<%= link_to 'Back', app_notifications_path %>